name: Run Tests Private Final

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set Java 23
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '23'
    
    - name: Install B2 CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install b2
    
    - name: Configure Backblaze B2 credentials
      run: |
        b2 authorize-account ${{ secrets.B2_APPLICATION_KEY_ID }} ${{ secrets.B2_APPLICATION_KEY }}
    
    - name: Download closed-source JAR from B2
      run: |
        b2 download-file-by-name ${{ secrets.B2_BUCKET_NAME }} ${{ secrets.B2_FILE_NAME }} ./src/lib/po-uilib.jar
    

    - name: Run the private test script
      run: |
        chmod +x ./scripts/runtestspublic.sh
        ./scripts/runtestspublic.sh