name: Run Private Final Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set Java 23
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '23'
    
    - name: Install B2 CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install b2
    
    - name: Configure Backblaze B2 credentials
      run: |
        b2 account authorize ${{ secrets.B2_APPLICATION_KEY_ID }} ${{ secrets.B2_APPLICATION_KEY }}
    
    - name: Download closed-source JAR from B2
      run: |
        b2 file download b2id://4_z3bc43694712ac5f29a2a091a_f10565276cab17389_d20241027_m192901_c003_v0312000_t0002_u01730057341715 ./src/lib/po-uilib.jar
    
    - name: Run the private final test script
      run: |
        chmod +x ./scripts/runtestsfinalprivate.sh
        ./scripts/runtestsfinalprivate.sh