name: Run Tests Private Final

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set Java 23
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '23'
    
    - name: Download and decode closed-source JAR
      run: |
        echo "${{ secrets.CLOSED_SOURCE_PO_UILIB }}" | base64 --decode > /src/lib/po-uilib.jar

    - name: Run the private test script
      run: |
        chmod +x ./scripts/runtestsfinalpublic.sh
        ./scripts/runtestsfinalpublic.sh