name: Run Private Final Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set Java 23
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '23'
    
    - name: Install B2 CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install b2
    
    - name: Configure Backblaze B2 credentials
      run: |
        b2 account authorize ${{ secrets.B2_APPLICATION_KEY_ID }} ${{ secrets.B2_APPLICATION_KEY }}
    
    - name: Create directory for JAR file
      run: mkdir -p ./src/lib

    - name: Download closed-source JAR from B2
      run: |
        b2 file download b2id://4_z3bc43694712ac5f29a2a091a_f10870e56b0dd76a4_d20250115_m112153_c003_v0312024_t0049_u01736940113462 ./src/lib/po-uilib.jar
    
    - name: Run the Private Final Tests script
      run: |
        chmod +x ./scripts/runtestsfinalprivate.sh
        ./scripts/runtestsfinalprivate.sh